/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAaveLendingPool,
  IAaveLendingPoolInterface,
} from "../../interfaces/IAaveLendingPool";

const _abi = [
  {
    inputs: [],
    name: "flashLoanFeePercentage",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAaveLendingPool__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveLendingPoolInterface {
    return new Interface(_abi) as IAaveLendingPoolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAaveLendingPool {
    return new Contract(address, _abi, runner) as unknown as IAaveLendingPool;
  }
}
