/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as flashloanSol from "./Flashloan.sol";
export * as uniswapV2InterfacesSol from "./UniswapV2Interfaces.sol";
