/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flashloanSol from "./Flashloan.sol";
export type { flashloanSol };
import type * as uniswapV2InterfacesSol from "./UniswapV2Interfaces.sol";
export type { uniswapV2InterfacesSol };
