/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  UniswapFlashSwapper,
  UniswapFlashSwapperInterface,
} from "../UniswapFlashSwapper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "uniswapV2Call",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class UniswapFlashSwapper__factory {
  static readonly abi = _abi;
  static createInterface(): UniswapFlashSwapperInterface {
    return new Interface(_abi) as UniswapFlashSwapperInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): UniswapFlashSwapper {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as UniswapFlashSwapper;
  }
}
